services:
  ######################
  # Consumer services ##
  ######################
  consumer-0:
    restart: no
    environment:
      DCR_SYNC_BASE_URL: https://dev.harvesting-self-service.lblod.info/
      DCR_CRON_PATTERN_DELTA_SYNC: 0 */5 * * * * # Every 5 minutes
      NODE_ENV: development
  consumer-1:
    restart: no
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: 0 */5 * * * * # Every 5 minutes
      NODE_ENV: development
    profiles:
      - all-consumers # When running all consumers it uses the test endpoint here
  consumer-2:
    restart: no
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: 0 */5 * * * * # Every 5 minutes
      NODE_ENV: development
    profiles:
      - all-consumers # When running all consumers it uses the test endpoint here
  consumer-3:
    restart: no
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: 0 */5 * * * * # Every 5 minutes
      NODE_ENV: development
    profiles:
      - all-consumers # When running all consumers it uses the test endpoint here
  ######################
  # LDES              ##
  ######################
  ldes-backend:
    environment:
      NODE_ENV: development
      BASE_URL: http://localhost/streams/ldes/
  ldes-delta-pusher:
    restart: no
    environment:
      NODE_ENV: development
      LDES_BASE: http://localhost/streams/ldes
      CRON_PATTERN_CLEANUP: '*/2 * * * *' # Every 2 minutes
  ##################
  # Base services ##
  ##################
  identifier:
    restart: no
    ports:
      - 81:80
  dispatcher:
    restart: no
  deltanotifier:
    restart: no
  database:
    restart: no
  virtuoso:
    restart: no
    ports:
      - 8891:8890
  modified:
    restart: no
    environment:
      NODE_ENV: development
