services:
  consumer-0:
    restart: 'no'
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  consumer-1:
    restart: 'no'
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  consumer-2:
    restart: 'no'
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  consumer-3:
    restart: 'no'
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  jobs-dashboard:
    restart: 'no'
  publication-triplestore:
    ports:
      - '8891:8890'
    restart: 'no'
  jobs-controller:
    restart: 'no'
  delta-producer-background-jobs-initiator:
    restart: 'no'
  delta-producer-publication-graph-maintainer:
    restart: 'no'
  delta-producer-dump-file-publisher:
    restart: 'no'
  identifier:
    restart: 'no'
  dispatcher:
    restart: 'no'
  deltanotifier:
    restart: 'no'
  database:
    restart: 'no'
  virtuoso:
    restart: 'no'
    ports:
      - '8890:8890'
  modified:
    restart: 'no'
