services:
  ######################
  # Consumer services ##
  ######################
  consumer-0:
    restart: no
    environment:
      DCR_SYNC_BASE_URL: 'https://dev.harvesting-self-service.lblod.info/'
      DCR_CRON_PATTERN_DELTA_SYNC: 0/15 * * * * *
      NODE_ENV: development
    ports:
      - 9224:9229
  consumer-1:
    restart: no
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: 0/15 * * * * *
      NODE_ENV: development
    profiles:
      - consumer
  consumer-2:
    restart: no
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: 0/15 * * * * *
      NODE_ENV: development
    profiles:
      - consumer
  consumer-3:
    restart: no
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: 0/15 * * * * *
      NODE_ENV: development
    profiles:
      - consumer
  ######################
  # LDES              ##
  ######################
  ldes-backend:
    environment:
      NODE_ENV: development
  ldes-delta-pusher:
    restart: no
    environment:
      NODE_ENV: development
    ports:
      - 9225:9229
  ##################
  # Base services ##
  ##################
  identifier:
    restart: no
    ports:
      - 81:80
  dispatcher:
    restart: no
  deltanotifier:
    restart: no
  database:
    restart: no
  virtuoso:
    restart: no
    ports:
      - 8891:8890
