services:
  consumer-0:
    restart: 'no'
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  consumer-1:
    restart: 'no'
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  consumer-2:
    restart: 'no'
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  consumer-3:
    restart: 'no'
    environment:
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  jobs-dashboard:
    restart: 'no'
    ports:
      - 82:80
  publication-triplestore:
    ports:
      - '8892:8890'
    restart: 'no'
  jobs-controller:
    restart: 'no'
  delta-producer-background-jobs-initiator:
    restart: 'no'
    environment:
      NODE_ENV: development
  delta-producer-publication-graph-maintainer:
    restart: 'no'
  delta-producer-dump-file-publisher:
    restart: 'no'
  identifier:
    restart: 'no'
    ports:
      - '81:80'
    networks:
      deltas-sync:
        aliases:
          - producer-identifier
      default:
        aliases:
          - identifier
  dispatcher:
    restart: 'no'
  deltanotifier:
    restart: 'no'
  database:
    restart: 'no'
  virtuoso:
    restart: 'no'
    ports:
      - '8891:8890'
  modified:
    restart: 'no'

networks:
  deltas-sync:
    driver: bridge
    name: deltas-sync