services:
  consumer-0:
    restart: 'no'
    environment:
      # DCR_SYNC_BASE_URL: 'https://dev.harvesting-self-service.lblod.info/'
      DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
      # BATCH_SIZE: 10
      DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
      NODE_ENV: development
    ports:
      - 9224:9229
    networks:
      - debug
  # consumer-1:
  #   restart: 'no'
  #   profiles:
  #     - qaConsumer-1
  #   environment:
  #     DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
  #     DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  # consumer-2:
  #   restart: 'no'
  #   profiles:
  #     - qaConsumer-2
  #   environment:
  #     DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
  #     DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  # consumer-3:
  #   restart: 'no'
  #   profiles:
  #     - qaConsumer-3
  #   environment:
  #     DCR_CRON_PATTERN_DELTA_SYNC: '0/15 * * * * *'
  #     DCR_START_FROM_DELTA_TIMESTAMP: '2024-01-12T15:51:23.478Z'
  ldes-backend:
    environment:
      NODE_ENV: development
    networks:
      - debug
  ldes-delta-pusher:
    restart: no
    environment:
      NODE_ENV: development
    ports:
      - 9225:9229
    networks:
      - debug
  identifier:
    restart: 'no'
    ports:
      - '81:80'
    networks:
      - debug
  dispatcher:
    restart: 'no'
  deltanotifier:
    restart: 'no'
  database:
    restart: 'no'
    networks:
      - debug
  virtuoso:
    restart: 'no'
    ports:
      - '8891:8890'
    networks:
      - debug
  modified:
    restart: 'no'

networks:
  debug:
    driver: bridge
    name: debug
